# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 69b2663
_src_path: git+https://git.sr.ht/~emmabastas/min-template
changelog: false
editorconfig: true
gitinit: gh
gitreponame: ez-static-i18n
license: true
name: ez-static-i18n
nix: true
projectType: []
